chore(ts): small tweaks to make typescript happier
yargs/cliui pull request #137
Opened 2023-04-28 23:31 UTC by isaacs

- Use trimStart/trimEnd instead of deprecated trimLeft/trimRight
- Target es2019, which is when trimLeft/Right/Start/End methods became available (at least according to tsc)

2023-04-29 05:45 UTC, shadowspawn commented
These changes look reasonable, but under what circumstances does TypeScript complain?

(I am not seeing any messages from running `tsc`, or in Visual Studio.)

2023-04-29 16:13 UTC, isaacs commented
The ts server in neovim warned about them. Maybe I have a different typescript version or something? Or it could be using ts lint? I've found its advice is usually pretty good.

2023-04-29 22:35 UTC, shadowspawn commented
https://exploringjs.com/es2018-es2019/ch_array-prototype-trimstart-trimend.html

> Many web browsers have the string methods .trimLeft() and .trimRight(). Those were added to Annex B of the ECMAScript specification (as aliases for .trimStart() and .trimEnd()): features that are required for web browsers and optional elsewhere.

https://tc39.es/ecma262/

> ECMAScript 2019 introduced a few new built-in functions: ... trimStart and trimEnd on String.prototype as better-named alternatives to the widely implemented but non-standard String.prototype.trimLeft and trimRight built-ins.

Node.js has `trimStart` and `trimEnd` in v12: https://node.green

2023-04-29 22:45 UTC, shadowspawn commented
The Typescript configuration docs mention `trimStart` in the lib section (lib change is implied by changing target):
https://www.typescriptlang.org/tsconfig#lib

2023-04-29 22:49 UTC, shadowspawn approved these changes
LGTM
The change to target makes this semver major, but I expect we'll be doing a release to drop node 12 (and maybe 14 too) at some point anyway.

2023-04-30 00:11 UTC, shadowspawn commented
I finally managed to get some warnings from tsc compile by removing `@types/node`, which has:

```
// Node.js ESNEXT support
interface String {
    /** Removes whitespace from the left end of a string. */
    trimLeft(): string;
    /** Removes whitespace from the right end of a string. */
    trimRight(): string;

    /** Returns a copy with leading whitespace removed. */
    trimStart(): string;
    /** Returns a copy with trailing whitespace removed. */
    trimEnd(): string;
}
```

So Typescript is happy when used directly, and I suspect the ts-server (or tslint) in your neovim setup is using somewhat different configuration, or ignoring node context.

2023-04-30 01:38 UTC, isaacs commented
Dropping everything before 14 at least is a good idea.

2023-04-30 04:02 UTC, shadowspawn requested changes
I am ok with changing trim calls, but I do not want to change `target` in `tsconfig.json` without a clear idea what scenario that benefits.

2023-05-02 03:21 UTC, isaacs commented
subsumed in #139, closing this one so I can make some changes on my main branch.

2023-05-02 03:21 UTC, closed without merging